# Generated by Django 5.1.4 on 2024-12-13 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataHandle', '0002_alter_userdata_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userData',
        ),
    ]
