# Generated by Django 5.1.4 on 2024-12-14 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataHandle', '0005_usersdata_delete_userdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='loginHistory',
            fields=[
                ('loginId', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('userId', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=16)),
                ('validate', models.BooleanField()),
                ('returnName', models.CharField(max_length=50)),
                ('returnPhone', models.BigIntegerField()),
                ('returnEmail', models.CharField(max_length=60)),
                ('returnUserId', models.CharField(max_length=20)),
                ('loginTime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
