# Generated by Django 5.1.4 on 2024-12-14 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataHandle', '0006_loginhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginhistory',
            name='returnEmail',
        ),
        migrations.RemoveField(
            model_name='loginhistory',
            name='returnName',
        ),
        migrations.RemoveField(
            model_name='loginhistory',
            name='returnPhone',
        ),
        migrations.RemoveField(
            model_name='loginhistory',
            name='returnUserId',
        ),
    ]
