# Generated by Django 5.1.4 on 2024-12-14 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataHandle', '0007_remove_loginhistory_returnemail_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='loginHistory',
        ),
    ]
