# Generated by Django 5.1.4 on 2024-12-14 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataHandle', '0008_delete_loginhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='loginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=16)),
                ('validate', models.BooleanField()),
                ('loginTime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
