# Generated by Django 5.1.4 on 2024-12-15 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataHandle', '0009_loginhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='localData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.BigIntegerField()),
                ('email', models.CharField(max_length=60)),
                ('userId', models.CharField(max_length=20)),
            ],
        ),
    ]
