# Generated by Django 5.1.4 on 2024-12-16 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataHandle', '0010_localdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='localData',
        ),
    ]
