# Generated by Django 5.1.4 on 2024-12-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataHandle', '0011_delete_localdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='carsList',
            fields=[
                ('carId', models.AutoField(primary_key=True, serialize=False)),
                ('ownerName', models.CharField(max_length=50)),
                ('ownerPhone', models.BigIntegerField()),
                ('ownerAddress', models.CharField(max_length=100)),
                ('carModel', models.CharField(max_length=100)),
                ('carRent', models.IntegerField()),
                ('carImage', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
