# Generated by Django 5.1.4 on 2024-12-17 05:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataHandle', '0012_carslist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginhistory',
            name='loginTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('bookId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.BigIntegerField()),
                ('pickup', models.CharField(max_length=150)),
                ('pickupDate', models.DateField()),
                ('drop', models.CharField(max_length=150)),
                ('dropDate', models.DateField()),
                ('bookingDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataHandle.carslist')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataHandle.usersdata')),
            ],
        ),
    ]
