# Generated by Django 5.1.4 on 2024-12-17 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataHandle', '0013_alter_loginhistory_logintime_bookings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='car',
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='userId',
        ),
        migrations.DeleteModel(
            name='loginHistory',
        ),
        migrations.DeleteModel(
            name='carsList',
        ),
        migrations.DeleteModel(
            name='Bookings',
        ),
        migrations.DeleteModel(
            name='usersData',
        ),
    ]
