# Generated by Django 5.1.4 on 2024-12-17 07:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dataHandle', '0014_remove_bookings_car_remove_bookings_userid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='carsList',
            fields=[
                ('carId', models.AutoField(primary_key=True, serialize=False)),
                ('ownerName', models.CharField(max_length=50)),
                ('ownerPhone', models.BigIntegerField()),
                ('ownerAddress', models.CharField(max_length=100)),
                ('carModel', models.CharField(max_length=100)),
                ('carRent', models.IntegerField()),
                ('carImage', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='loginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=16)),
                ('validate', models.BooleanField()),
                ('loginTime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='usersData',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('phone', models.BigIntegerField()),
                ('email', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=50)),
                ('userId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('bookId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.BigIntegerField()),
                ('pickup', models.CharField(max_length=150)),
                ('pickupDate', models.DateField()),
                ('drop', models.CharField(max_length=150)),
                ('dropDate', models.DateField()),
                ('bookingDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataHandle.carslist')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataHandle.usersdata')),
            ],
        ),
    ]
